name: Docker Image CI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    
    environment: docker-publish

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/momiji/basic-to-passport-auth-http-proxy:${{github.ref_name}}
    - name: Publish the Docker image
      run: docker push ghcr.io/momiji/basic-to-passport-auth-http-proxy:${{github.ref_name}}
